# Generated by Django 5.2.4 on 2025-09-12 15:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('street', models.CharField(max_length=120)),
                ('street_no', models.CharField(max_length=20)),
                ('zip_code', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=60)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('items', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='created', max_length=20)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='tickets/')),
            ],
        ),
    ]
